USE projeto;

CREATE TABLE
    IF NOT EXISTS Users(
        id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
        name VARCHAR(70) NOT NULL,
        email VARCHAR(100) NOT NULL UNIQUE,
        password VARCHAR(255) NOT NULL,
        token VARCHAR(255) UNIQUE,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    )  ENGINE = InnoDB;

CREATE TABLE
    IF NOT EXISTS Produtos (
        id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
        nome VARCHAR(100) NOT NULL,
        preco DECIMAL(9, 2) NOT NULL,
        quantidade INT NOT NULL DEFAULT 0,
        disponivel BOOL NOT NULL DEFAULT TRUE,
        categoria VARCHAR(100) NOT NULL,
        imageURL VARCHAR(255) NOT NULL,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    ) ENGINE = InnoDB;